version: '3'
services: 
  server: 
    build: ./server
    container_name: pretty_note_server
    restart: always
    networks:
      - prettynote
  bot:
    build: ./bot
    container_name: pretty_note_bot
    restart: always
    ports: 
      - "8000:8000"
    networks:
      - prettynote
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "0.0.0.0:443:443"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./nginx/credential.pem:/etc/nginx/credential.pem:ro" #change your own key
      - "./nginx/credential.key:/etc/nginx/credential.key:ro"
      - "./nginx/credential.store.pem:/etc/nginx/credential.store.pem:ro"
      - "./nginx/credential.store.key:/etc/nginx/credential.store.key:ro"
    networks:
      - prettynote

networks:
  prettynote: {}
