version: "3"
services:
  apisystemmysql:
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    container_name: apisystemmysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
      MYSQL_DATABASE: spring
    networks:
      extnetwork2:
        ipv4_address: 172.192.1.200

  APISystem:
    build: ./APISystem
    image: nctf2021/apisystem
    container_name: apisystem
    restart: always
    entrypoint: /start.sh
    ports: 
      - "58082:8080"
    depends_on:
      - apisystemmysql
    networks:
      extnetwork2:
        ipv4_address: 172.192.1.10    

networks:
  extnetwork2:
    # internal: true
    ipam:
      config:
      - subnet: 172.192.1.0/24
        gateway:  172.192.1.1
